// Generated by GraphWalker (http://www.graphwalker.org)
package br.com.unicamp.inf321.gr3;

import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "br/com/unicamp/inf321/Lab1-Grupo3-Completo.graphml")
public interface Lab1Grupo3Completo {

    @Vertex()
    void v_ClientNotRunning();

    @Vertex()
    void v_TelaCriarConta();

    @Edge()
    void e_back();

    @Vertex()
    void v_FinalizarPedido();

    @Edge()
    void e_pesquisar_palavra_chave();

    @Edge()
    void e_opcao_criar();

    @Edge()
    void e_Adicionar_no_carrinho();

    @Edge()
    void e_detalhar_Produto();

    @Vertex()
    void V_Tela_Home();

    @Vertex()
    void v_BoasVindasNovaConta();

    @Vertex()
    void V_Tela_de_detalhe_de_produto();

    @Vertex()
    void v_Tela_de_detalhe_de_produto();

    @Edge()
    void e_tipo_conta();

    @Vertex()
    void v_TelaBoasVindasContaExistente();

    @Edge()
    void e_pesquisar_mais_de_uma_palavra_chave();

    @Vertex()
    void v_TelaRecuperarSenha();

    @Vertex()
    void V_Tela_Resultado_Pesquisa();

    @Vertex()
    void v_TelaEscolhaOpcao();

    @Vertex()
    void V_Tela_PopUp();

    @Vertex()
    void v_Tela_de_carrinho();

    @Vertex()
    void v_Foto_navegada();

    @Edge()
    void e_opcao_logar();

    @Edge()
    void e_boasVindas();

    @Vertex()
    void v_Tela_de_Pedido();

    @Edge()
    void e_Navegar_foto();

    @Edge()
    void e_Exit();

    @Edge()
    void e_Comprar_na_hora();

    @Edge()
    void e_Logar();

    @Edge()
    void e_fecharTelaDetalhamento();

    @Edge()
    void e_Home();

    @Edge()
    void e_FecharCompra();

    @Edge()
    void e_opcao();

    @Edge()
    void e_pesquisar_uma_palavra_chave();

    @Edge()
    void e_pesquisar_vazio();

    @Edge()
    void e_opcao_esq();

    @Vertex()
    void v_TelaLogin();

    @Vertex()
    void v_TelaPrincipal();

    @Edge()
    void e_opcao_entrar();

    @Edge()
    void e_voltar_Tela_Home();

    @Edge()
    void e_segue();
}
