// Generated by GraphWalker (http://www.graphwalker.org)
package br.com.unicamp.inf321;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "br/com/unicamp/inf321/AmazonShoppingOfertas.graphml")
public interface AmazonShoppingOfertas {

    @Edge()
    void e_Iniciar();

    @Vertex()
    void v_TelaEsqueciASenha();

    @Edge()
    void e_VoltarCadastro();

    @Edge()
    void e_AcessarCadastroPeloLogin();

    @Edge()
    void e_VoltarLogin();

    @Edge()
    void e_AcessarEsqueciASenha();

    @Edge()
    void e_UsarEmail();

    @Edge()
    void e_AcessarLoginPeloCadastro();

    @Vertex()
    void v_TelaCadastro();

    @Edge()
    void e_VoltarBoasVindas();

    @Vertex()
    void v_BoasVindas();

    @Edge()
    void e_AcessarCadastro();

    @Vertex()
    void v_TelaLogin();

    @Edge()
    void e_UsarTelefone();

    @Edge()
    void e_AcessarLogin();
}
