// Generated by GraphWalker (http://www.graphwalker.org)
package br.com.unicamp.inf321;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "br/com/unicamp/inf321/tela_detalhe_produto.graphml")
public interface tela_detalhe_produto {

    @Vertex()
    void v_Tela_de_detalhe_de_produto();

    @Vertex()
    void v_Tela_de_carrinho();

    @Vertex()
    void v_Foto_navegada();

    @Edge()
    void e_Adicionar_no_carrinho();

    @Edge()
    void eStartDetalhe();

    @Vertex()
    void v_Tela_de_Pedido();

    @Edge()
    void e_Navegar_foto();

    @Edge()
    void e_Comprar_na_hora();
}
